#!/usr/bin/env python3
"""
Generate INDEX.md: annotated file list for agent orientation.
Commits INDEX.md if it changed.

Usage:
    python3 scripts/generate-index.py
"""

import glob
import json
import os
import subprocess


def run(cmd):
    try:
        return subprocess.check_output(cmd, text=True, stderr=subprocess.PIPE).strip()
    except subprocess.CalledProcessError as e:
        cmd_str = " ".join(cmd)
        stderr = e.stderr.strip() if e.stderr else ""
        msg = f"Command failed: {cmd_str}"
        if stderr:
            msg += f"\n{stderr}"
        raise SystemExit(msg) from None


def annotate(path, plugin_name):
    basename = os.path.basename(path)

    if plugin_name:
        prefix = f"plugins/{plugin_name}/"
        rel = path[len(prefix):]
        rel_parts = rel.split("/")

        if rel == ".claude-plugin/plugin.json":
            return "Plugin manifest"
        if rel == "CLAUDE.md":
            return "Runtime instructions (ships with plugin)"
        if rel == "DISCLAIMER.md":
            return "Disclaimer"
        if rel_parts[0] == "skills" and len(rel_parts) >= 3 and rel_parts[2] == "SKILL.md":
            return f"`/{plugin_name}:{rel_parts[1]}` skill"
        if rel_parts[0] == "skills" and len(rel_parts) >= 3 and rel_parts[2] == "DESIGN.md":
            return f"Design decisions: `/{plugin_name}:{rel_parts[1]}`"
        if rel_parts[0] == "commands" and basename.endswith(".md"):
            return f"`/{plugin_name}:{basename[:-3]}` command"
        if rel_parts[0] == "design" and basename.endswith(".md"):
            return f"Design decisions: `/{plugin_name}:{basename[:-3]}` command"
        if rel == "hooks/hooks.json":
            return "Hook registry"
        if rel == "hooks/DESIGN.md":
            return "Design decisions: hooks"
        if rel_parts[0] == "hooks" and basename.endswith(".sh"):
            return "Hook script"
        if rel_parts[0] == "scripts":
            return f"Script: {basename}"
        return ""

    if path == ".claude-plugin/marketplace.json":
        return "Marketplace listing"
    if path == "CLAUDE.md":
        return "Developer instructions"
    if path == "README.md":
        return "Project README"
    if path == "LICENSE":
        return "License"
    if path == "TODO.md":
        return "Work tracking"
    if path == "TERMS-DRAFT.md":
        return "Terms draft"
    if path == ".gitignore":
        return "Git ignore rules"
    if basename == "MEMORY.md":
        return "Agent memory index"
    if path.startswith(".claude/hooks/") and basename.endswith(".sh"):
        return "Hook script"
    if path == ".claude/hooks/DESIGN.md":
        return "Hook design decisions"
    if path == ".claude/settings.json":
        return "Claude Code settings"
    if path.startswith(".github/") and basename.endswith(".md"):
        return "GitHub Actions design decisions"
    if basename.endswith(".py"):
        return f"Script: {basename}"
    return ""


def generate():
    tracked = run(["git", "ls-files"]).splitlines()
    plugin_dirs = sorted(d for d in glob.glob("plugins/*/") if os.path.isdir(d))
    plugin_names = [os.path.basename(d.rstrip("/")) for d in plugin_dirs]

    lines = [
        "# INDEX",
        "",
        "<!-- Auto-generated by scripts/generate-index.py. Do not edit manually. -->",
        "",
    ]

    indexed_files = set()
    for plugin_name, plugin_dir in zip(plugin_names, plugin_dirs):
        plugin_json = os.path.join(plugin_dir, ".claude-plugin/plugin.json")
        version = ""
        if os.path.exists(plugin_json):
            with open(plugin_json, encoding="utf-8") as f:
                try:
                    data = json.load(f)
                except json.JSONDecodeError:
                    data = {}
                version = data.get("version", "") if isinstance(data, dict) else ""

        version_str = f" (v{version})" if version else ""
        lines += [
            f"## Plugin: {plugin_name}{version_str}",
            "",
            "| Path | Role |",
            "|---|---|",
        ]
        prefix = plugin_dir.rstrip("/") + "/"
        plugin_tracked = sorted(f for f in tracked if f.startswith(prefix))
        for f in plugin_tracked:
            lines.append(f"| `{f}` | {annotate(f, plugin_name)} |")
            indexed_files.add(f)
        lines.append("")

    root_files = sorted(f for f in tracked if f not in indexed_files and f != "INDEX.md")
    if root_files:
        lines += [
            "## Repository root",
            "",
            "| Path | Role |",
            "|---|---|",
        ]
        for f in root_files:
            lines.append(f"| `{f}` | {annotate(f, None)} |")
        lines.append("")

    return "\n".join(lines)


def main():
    os.chdir(run(["git", "rev-parse", "--show-toplevel"]))
    content = generate()
    index_path = "INDEX.md"

    abs_path = os.path.abspath(index_path)
    tmp = abs_path + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    os.replace(tmp, abs_path)

    subprocess.run(["git", "add", index_path], check=True)

    # Let git decide if there's anything new to commit.
    diff = subprocess.run(
        ["git", "diff", "--cached", "--quiet", "--", index_path], check=False
    )
    if diff.returncode == 0:
        subprocess.run(["git", "reset", "HEAD", "--", index_path], check=False)
        print("INDEX.md is up to date.")
        return

    subprocess.run(
        ["git", "commit", "--only", "-m", "chore: refresh INDEX.md", "--", index_path],
        check=True,
    )
    print("INDEX.md updated and committed.")


if __name__ == "__main__":
    main()
